#!/bin/bash

# The variables defined here are available not only in BES logs, but also for
# stamping into built binaries (version information, etc.). Removing vars or
# changing var names may break these version stamping libraries; if this script
# is updated, also make sure the following are up-to-date:
#
# - //internal/buildstamp/BUILD

echo BUILD_SCM_BRANCH $(git rev-parse --abbrev-ref HEAD)
echo BUILD_SCM_REVISION $(git rev-parse --verify HEAD)

git diff-index --quiet HEAD --
if [[ $? == 0 ]]; then
  status="clean"
else
  status="modified"
fi
echo BUILD_SCM_STATUS $status

REMOTE_URL=$(git remote get-url origin)
if [[ $? == 0 ]]; then
  echo BUILD_SCM_REMOTE $REMOTE_URL
fi
