load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "httputil",
    srcs = ["header_transport.go"],
    importpath = "github.com/EngFlow/auth/internal/httputil",
    visibility = ["//:__subpackages__"],
)
