load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "autherr",
    srcs = ["coded_error.go"],
    importpath = "github.com/EngFlow/auth/internal/autherr",
    visibility = ["//third_party/engflow_auth:__subpackages__"],
)
