load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "browser",
    srcs = ["browser.go"],
    importpath = "github.com/EngFlow/auth/internal/browser",
    visibility = ["//third_party/engflow_auth:__subpackages__"],
)
