load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "browser",
    srcs = ["browser.go"],
    importpath = "github.com/EngFlow/auth/internal/browser",
    visibility = ["//:__subpackages__"],
)
