# Copyright 2024 EngFlow Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "release"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of engflow_auth to release; must be a semver version string, starting with `v`
        required: true
      dry_run:
        type: boolean
        description: "Dry run: if checked, all artifacts are built, but no release is created."
        required: true

permissions:
  contents: write

env:
  # TODO(REC-55): use real certificate.
  APPLE_CERT_BASE64: ${{ secrets.APPLE_DEV_CERT_BASE64 }}
  # Recommended here: https://github.com/bazelbuild/bazelisk/issues/88#issuecomment-625178467
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER_HOST: opal.cluster.engflow.com
  CRED_HELPER_TOKEN: ${{ secrets.OPAL_CRED_HELPER_TOKEN }}
  DRY_RUN: ${{ inputs.dry_run }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4
      - run: infra/release-check.sh

  build-artifacts:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    needs:
      - check-version

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "linux"
            arch: "x64"
            runner: "ubuntu-latest"

          - os: "macos"
            arch: "arm64"
            runner: "macos-14"

          - os: "windows"
            arch: "x64"
            runner: "windows-2022"

    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in
        run: infra/login.sh
        shell: bash

      - name: Build release artifacts
        if: success()
        run: infra/release-build.sh
        shell: bash

      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ matrix.os }}
          path: _out
          if-no-files-found: error
          retention-days: 1
          overwrite: true

      - name: Log out
        run: infra/logout.sh
        shell: bash

  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-artifacts

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: _out
          merge-multiple: true
      - run: infra/release-create.sh
